### ISSUE TITLE
Platform Compatibility

### ISSUE THREAD

**Issue by Dachui66** [cj-mills/byte-track-eigen#1]
Thank you for your open-source contribution. I think we can modify include/Export.h like this to enable cross-platform compilation.
```cpp
#ifdef BUILDING_BYTE_TRACK_EIGEN
    #ifdef _WIN32
        #define BYTE_TRACK_EIGEN_API __declspec(dllexport)
    #else
        #define BYTE_TRACK_EIGEN_API __attribute__((visibility("default")))
    #endif
#else
    #ifdef _WIN32
        #define BYTE_TRACK_EIGEN_API __declspec(dllimport)
    #else
        #define BYTE_TRACK_EIGEN_API
    #endif
#endif
```

**Comment by Dachui66** [comment]
The following modifications are also needed:

    Add #include <memory> in the include/KalmanBBoxTrack.h file.
    Add #include <cfloat> in the src/HungarianAlgorithmEigen.cpp file.

**Comment by cj-mills** [comment]
Hi @Dachui66,
Thanks for taking the time here and in your other issues to report your findings from getting the library working in Linux!
My schedule got busy before I could test the project on Linux. I'll try making time to test your suggested changes and push a new release this weekend.
Thanks again!
